version: '3'

services:
    nginx:
        build: requirements/nginx/
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped